/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_gtaun_shoebill_samp_SampNativeFunction */

#ifndef _Included_net_gtaun_shoebill_samp_SampNativeFunction
#define _Included_net_gtaun_shoebill_samp_SampNativeFunction
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    setServerCodepage
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_setServerCodepage
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    getServerCodepage
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_getServerCodepage
  (JNIEnv *, jclass);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    setPlayerCodepage
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_setPlayerCodepage
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    getPlayerCodepage
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_getPlayerCodepage
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    createObject
 * Signature: (IFFFFFFF)I
 */
JNIEXPORT jint JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_createObject
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    attachObjectToVehicle
 * Signature: (IIFFFFFF)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_attachObjectToVehicle
  (JNIEnv *, jclass, jint, jint, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    attachObjectToObject
 * Signature: (IIFFFFFFI)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_attachObjectToObject
  (JNIEnv *, jclass, jint, jint, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    attachObjectToPlayer
 * Signature: (IIFFFFFF)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_attachObjectToPlayer
  (JNIEnv *, jclass, jint, jint, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    setObjectPos
 * Signature: (IFFF)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_setObjectPos
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    getObjectPos
 * Signature: (ILnet/gtaun/shoebill/data/Vector3D;)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_getObjectPos
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    setObjectRot
 * Signature: (IFFF)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_setObjectRot
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    getObjectRot
 * Signature: (ILnet/gtaun/shoebill/data/Vector3D;)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_getObjectRot
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    isValidObject
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_isValidObject
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    destroyObject
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_destroyObject
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    moveObject
 * Signature: (IFFFFFFF)I
 */
JNIEXPORT jint JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_moveObject
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    stopObject
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_stopObject
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    isObjectMoving
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_isObjectMoving
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    createPlayerObject
 * Signature: (IIFFFFFFF)I
 */
JNIEXPORT jint JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_createPlayerObject
  (JNIEnv *, jclass, jint, jint, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    setPlayerObjectPos
 * Signature: (IIFFF)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_setPlayerObjectPos
  (JNIEnv *, jclass, jint, jint, jfloat, jfloat, jfloat);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    getPlayerObjectPos
 * Signature: (IILnet/gtaun/shoebill/data/Vector3D;)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_getPlayerObjectPos
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    setPlayerObjectRot
 * Signature: (IIFFF)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_setPlayerObjectRot
  (JNIEnv *, jclass, jint, jint, jfloat, jfloat, jfloat);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    getPlayerObjectRot
 * Signature: (IILnet/gtaun/shoebill/data/Vector3D;)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_getPlayerObjectRot
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    isValidPlayerObject
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_isValidPlayerObject
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    destroyPlayerObject
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_destroyPlayerObject
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    movePlayerObject
 * Signature: (IIFFFFFFF)I
 */
JNIEXPORT jint JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_movePlayerObject
  (JNIEnv *, jclass, jint, jint, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    stopPlayerObject
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_stopPlayerObject
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    isPlayerObjectMoving
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_isPlayerObjectMoving
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    attachPlayerObjectToPlayer
 * Signature: (IIIFFFFFF)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_attachPlayerObjectToPlayer
  (JNIEnv *, jclass, jint, jint, jint, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    setSpawnInfo
 * Signature: (IIIFFFFIIIIII)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_setSpawnInfo
  (JNIEnv *, jclass, jint, jint, jint, jfloat, jfloat, jfloat, jfloat, jint, jint, jint, jint, jint, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    spawnPlayer
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_spawnPlayer
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    setPlayerPos
 * Signature: (IFFF)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_setPlayerPos
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    setPlayerPosFindZ
 * Signature: (IFFF)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_setPlayerPosFindZ
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    getPlayerPos
 * Signature: (ILnet/gtaun/shoebill/data/Vector3D;)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_getPlayerPos
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    setPlayerFacingAngle
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_setPlayerFacingAngle
  (JNIEnv *, jclass, jint, jfloat);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    getPlayerFacingAngle
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_getPlayerFacingAngle
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    isPlayerInRangeOfPoint
 * Signature: (IFFFF)Z
 */
JNIEXPORT jboolean JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_isPlayerInRangeOfPoint
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    isPlayerStreamedIn
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_isPlayerStreamedIn
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    setPlayerInterior
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_setPlayerInterior
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    getPlayerInterior
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_getPlayerInterior
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    setPlayerHealth
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_setPlayerHealth
  (JNIEnv *, jclass, jint, jfloat);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    getPlayerHealth
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_getPlayerHealth
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    setPlayerArmour
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_setPlayerArmour
  (JNIEnv *, jclass, jint, jfloat);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    getPlayerArmour
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_getPlayerArmour
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    setPlayerAmmo
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_setPlayerAmmo
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    getPlayerAmmo
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_getPlayerAmmo
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    getPlayerWeaponState
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_getPlayerWeaponState
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    getPlayerTargetPlayer
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_getPlayerTargetPlayer
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    setPlayerTeam
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_setPlayerTeam
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    getPlayerTeam
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_getPlayerTeam
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    setPlayerScore
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_setPlayerScore
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    getPlayerScore
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_getPlayerScore
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    getPlayerDrunkLevel
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_getPlayerDrunkLevel
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    setPlayerDrunkLevel
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_setPlayerDrunkLevel
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    setPlayerColor
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_setPlayerColor
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    getPlayerColor
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_getPlayerColor
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    setPlayerSkin
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_setPlayerSkin
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    getPlayerSkin
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_getPlayerSkin
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    givePlayerWeapon
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_givePlayerWeapon
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    resetPlayerWeapons
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_resetPlayerWeapons
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    setPlayerArmedWeapon
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_setPlayerArmedWeapon
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    getPlayerWeaponData
 * Signature: (IILnet/gtaun/shoebill/data/WeaponData;)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_getPlayerWeaponData
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    givePlayerMoney
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_givePlayerMoney
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    resetPlayerMoney
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_resetPlayerMoney
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    setPlayerName
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_setPlayerName
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    getPlayerMoney
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_getPlayerMoney
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    getPlayerState
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_getPlayerState
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    getPlayerIp
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_getPlayerIp
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    getPlayerPing
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_getPlayerPing
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    getPlayerWeapon
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_getPlayerWeapon
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    getPlayerKeys
 * Signature: (ILnet/gtaun/shoebill/object/PlayerKeyState;)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_getPlayerKeys
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    getPlayerName
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_getPlayerName
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    setPlayerTime
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_setPlayerTime
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    getPlayerTime
 * Signature: (ILnet/gtaun/shoebill/data/Time;)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_getPlayerTime
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    togglePlayerClock
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_togglePlayerClock
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    setPlayerWeather
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_setPlayerWeather
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    forceClassSelection
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_forceClassSelection
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    setPlayerWantedLevel
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_setPlayerWantedLevel
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    getPlayerWantedLevel
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_getPlayerWantedLevel
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    setPlayerFightingStyle
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_setPlayerFightingStyle
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    getPlayerFightingStyle
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_getPlayerFightingStyle
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    setPlayerVelocity
 * Signature: (IFFF)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_setPlayerVelocity
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    getPlayerVelocity
 * Signature: (ILnet/gtaun/shoebill/data/Velocity;)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_getPlayerVelocity
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    playCrimeReportForPlayer
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_playCrimeReportForPlayer
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    playAudioStreamForPlayer
 * Signature: (ILjava/lang/String;FFFFI)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_playAudioStreamForPlayer
  (JNIEnv *, jclass, jint, jstring, jfloat, jfloat, jfloat, jfloat, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    stopAudioStreamForPlayer
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_stopAudioStreamForPlayer
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    setPlayerShopName
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_setPlayerShopName
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    setPlayerSkillLevel
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_setPlayerSkillLevel
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    getPlayerSurfingVehicleID
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_getPlayerSurfingVehicleID
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    getPlayerSurfingObjectID
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_getPlayerSurfingObjectID
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    removeBuildingForPlayer
 * Signature: (IIFFFF)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_removeBuildingForPlayer
  (JNIEnv *, jclass, jint, jint, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    setPlayerAttachedObject
 * Signature: (IIIIFFFFFFFFF)Z
 */
JNIEXPORT jboolean JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_setPlayerAttachedObject
  (JNIEnv *, jclass, jint, jint, jint, jint, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    removePlayerAttachedObject
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_removePlayerAttachedObject
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    isPlayerAttachedObjectSlotUsed
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_isPlayerAttachedObjectSlotUsed
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    setPVarInt
 * Signature: (ILjava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_setPVarInt
  (JNIEnv *, jclass, jint, jstring, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    getPVarInt
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_getPVarInt
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    setPVarString
 * Signature: (ILjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_setPVarString
  (JNIEnv *, jclass, jint, jstring, jstring);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    getPVarString
 * Signature: (ILjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_getPVarString
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    setPVarFloat
 * Signature: (ILjava/lang/String;F)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_setPVarFloat
  (JNIEnv *, jclass, jint, jstring, jfloat);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    getPVarFloat
 * Signature: (ILjava/lang/String;)F
 */
JNIEXPORT jfloat JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_getPVarFloat
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    deletePVar
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_deletePVar
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    getPVarsUpperIndex
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_getPVarsUpperIndex
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    getPVarNameAtIndex
 * Signature: (II)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_getPVarNameAtIndex
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    getPVarType
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_getPVarType
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    setPlayerChatBubble
 * Signature: (ILjava/lang/String;IFI)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_setPlayerChatBubble
  (JNIEnv *, jclass, jint, jstring, jint, jfloat, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    putPlayerInVehicle
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_putPlayerInVehicle
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    getPlayerVehicleID
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_getPlayerVehicleID
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    getPlayerVehicleSeat
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_getPlayerVehicleSeat
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    removePlayerFromVehicle
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_removePlayerFromVehicle
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    togglePlayerControllable
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_togglePlayerControllable
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    playerPlaySound
 * Signature: (IIFFF)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_playerPlaySound
  (JNIEnv *, jclass, jint, jint, jfloat, jfloat, jfloat);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    applyAnimation
 * Signature: (ILjava/lang/String;Ljava/lang/String;FIIIIII)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_applyAnimation
  (JNIEnv *, jclass, jint, jstring, jstring, jfloat, jint, jint, jint, jint, jint, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    clearAnimations
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_clearAnimations
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    getPlayerAnimationIndex
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_getPlayerAnimationIndex
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    getPlayerSpecialAction
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_getPlayerSpecialAction
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    setPlayerSpecialAction
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_setPlayerSpecialAction
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    setPlayerCheckpoint
 * Signature: (IFFFF)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_setPlayerCheckpoint
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    disablePlayerCheckpoint
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_disablePlayerCheckpoint
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    setPlayerRaceCheckpoint
 * Signature: (IIFFFFFFF)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_setPlayerRaceCheckpoint
  (JNIEnv *, jclass, jint, jint, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    disablePlayerRaceCheckpoint
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_disablePlayerRaceCheckpoint
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    setPlayerWorldBounds
 * Signature: (IFFFF)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_setPlayerWorldBounds
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    setPlayerMarkerForPlayer
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_setPlayerMarkerForPlayer
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    showPlayerNameTagForPlayer
 * Signature: (IIZ)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_showPlayerNameTagForPlayer
  (JNIEnv *, jclass, jint, jint, jboolean);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    setPlayerMapIcon
 * Signature: (IIFFFIII)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_setPlayerMapIcon
  (JNIEnv *, jclass, jint, jint, jfloat, jfloat, jfloat, jint, jint, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    removePlayerMapIcon
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_removePlayerMapIcon
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    setPlayerCameraPos
 * Signature: (IFFF)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_setPlayerCameraPos
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    setPlayerCameraLookAt
 * Signature: (IFFF)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_setPlayerCameraLookAt
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    setCameraBehindPlayer
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_setCameraBehindPlayer
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    getPlayerCameraPos
 * Signature: (ILnet/gtaun/shoebill/data/Vector3D;)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_getPlayerCameraPos
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    getPlayerCameraFrontVector
 * Signature: (ILnet/gtaun/shoebill/data/Vector3D;)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_getPlayerCameraFrontVector
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    getPlayerCameraMode
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_getPlayerCameraMode
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    isPlayerConnected
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_isPlayerConnected
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    isPlayerInVehicle
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_isPlayerInVehicle
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    isPlayerInAnyVehicle
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_isPlayerInAnyVehicle
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    isPlayerInCheckpoint
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_isPlayerInCheckpoint
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    isPlayerInRaceCheckpoint
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_isPlayerInRaceCheckpoint
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    setPlayerVirtualWorld
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_setPlayerVirtualWorld
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    getPlayerVirtualWorld
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_getPlayerVirtualWorld
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    enableStuntBonusForPlayer
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_enableStuntBonusForPlayer
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    enableStuntBonusForAll
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_enableStuntBonusForAll
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    togglePlayerSpectating
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_togglePlayerSpectating
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    playerSpectatePlayer
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_playerSpectatePlayer
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    playerSpectateVehicle
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_playerSpectateVehicle
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    startRecordingPlayerData
 * Signature: (IILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_startRecordingPlayerData
  (JNIEnv *, jclass, jint, jint, jstring);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    stopRecordingPlayerData
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_stopRecordingPlayerData
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    sendClientMessage
 * Signature: (IILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_sendClientMessage
  (JNIEnv *, jclass, jint, jint, jstring);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    sendClientMessageToAll
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_sendClientMessageToAll
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    sendPlayerMessageToPlayer
 * Signature: (IILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_sendPlayerMessageToPlayer
  (JNIEnv *, jclass, jint, jint, jstring);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    sendPlayerMessageToAll
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_sendPlayerMessageToAll
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    sendDeathMessage
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_sendDeathMessage
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    gameTextForAll
 * Signature: (Ljava/lang/String;II)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_gameTextForAll
  (JNIEnv *, jclass, jstring, jint, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    gameTextForPlayer
 * Signature: (ILjava/lang/String;II)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_gameTextForPlayer
  (JNIEnv *, jclass, jint, jstring, jint, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    setTimer
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_setTimer
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    killTimer
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_killTimer
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    getMaxPlayers
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_getMaxPlayers
  (JNIEnv *, jclass);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    setGameModeText
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_setGameModeText
  (JNIEnv *, jclass, jstring);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    setTeamCount
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_setTeamCount
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    addPlayerClass
 * Signature: (IFFFFIIIIII)I
 */
JNIEXPORT jint JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_addPlayerClass
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat, jfloat, jint, jint, jint, jint, jint, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    addPlayerClassEx
 * Signature: (IIFFFFIIIIII)I
 */
JNIEXPORT jint JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_addPlayerClassEx
  (JNIEnv *, jclass, jint, jint, jfloat, jfloat, jfloat, jfloat, jint, jint, jint, jint, jint, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    addStaticVehicle
 * Signature: (IFFFFII)I
 */
JNIEXPORT jint JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_addStaticVehicle
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat, jfloat, jint, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    addStaticVehicleEx
 * Signature: (IFFFFIII)I
 */
JNIEXPORT jint JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_addStaticVehicleEx
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat, jfloat, jint, jint, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    addStaticPickup
 * Signature: (IIFFFI)I
 */
JNIEXPORT jint JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_addStaticPickup
  (JNIEnv *, jclass, jint, jint, jfloat, jfloat, jfloat, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    createPickup
 * Signature: (IIFFFI)I
 */
JNIEXPORT jint JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_createPickup
  (JNIEnv *, jclass, jint, jint, jfloat, jfloat, jfloat, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    destroyPickup
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_destroyPickup
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    showNameTags
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_showNameTags
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    showPlayerMarkers
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_showPlayerMarkers
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    gameModeExit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_gameModeExit
  (JNIEnv *, jclass);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    setWorldTime
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_setWorldTime
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    getWeaponName
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_getWeaponName
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    enableTirePopping
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_enableTirePopping
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    allowInteriorWeapons
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_allowInteriorWeapons
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    setWeather
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_setWeather
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    setGravity
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_setGravity
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    setDeathDropAmount
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_setDeathDropAmount
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    createExplosion
 * Signature: (FFFIF)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_createExplosion
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jint, jfloat);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    enableZoneNames
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_enableZoneNames
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    usePlayerPedAnims
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_usePlayerPedAnims
  (JNIEnv *, jclass);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    disableInteriorEnterExits
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_disableInteriorEnterExits
  (JNIEnv *, jclass);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    setNameTagDrawDistance
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_setNameTagDrawDistance
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    disableNameTagLOS
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_disableNameTagLOS
  (JNIEnv *, jclass);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    limitGlobalChatRadius
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_limitGlobalChatRadius
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    limitPlayerMarkerRadius
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_limitPlayerMarkerRadius
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    connectNPC
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_connectNPC
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    isPlayerNPC
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_isPlayerNPC
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    isPlayerAdmin
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_isPlayerAdmin
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    kick
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_kick
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    ban
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_ban
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    banEx
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_banEx
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    sendRconCommand
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_sendRconCommand
  (JNIEnv *, jclass, jstring);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    getServerVarAsString
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_getServerVarAsString
  (JNIEnv *, jclass, jstring);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    getServerVarAsInt
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_getServerVarAsInt
  (JNIEnv *, jclass, jstring);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    getServerVarAsBool
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_getServerVarAsBool
  (JNIEnv *, jclass, jstring);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    getPlayerNetworkStats
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_getPlayerNetworkStats
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    getNetworkStats
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_getNetworkStats
  (JNIEnv *, jclass);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    createMenu
 * Signature: (Ljava/lang/String;IFFFF)I
 */
JNIEXPORT jint JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_createMenu
  (JNIEnv *, jclass, jstring, jint, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    destroyMenu
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_destroyMenu
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    addMenuItem
 * Signature: (IILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_addMenuItem
  (JNIEnv *, jclass, jint, jint, jstring);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    setMenuColumnHeader
 * Signature: (IILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_setMenuColumnHeader
  (JNIEnv *, jclass, jint, jint, jstring);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    showMenuForPlayer
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_showMenuForPlayer
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    hideMenuForPlayer
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_hideMenuForPlayer
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    isValidMenu
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_isValidMenu
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    disableMenu
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_disableMenu
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    disableMenuRow
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_disableMenuRow
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    getPlayerMenu
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_getPlayerMenu
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    textDrawCreate
 * Signature: (FFLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_textDrawCreate
  (JNIEnv *, jclass, jfloat, jfloat, jstring);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    textDrawDestroy
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_textDrawDestroy
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    textDrawLetterSize
 * Signature: (IFF)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_textDrawLetterSize
  (JNIEnv *, jclass, jint, jfloat, jfloat);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    textDrawTextSize
 * Signature: (IFF)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_textDrawTextSize
  (JNIEnv *, jclass, jint, jfloat, jfloat);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    textDrawAlignment
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_textDrawAlignment
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    textDrawColor
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_textDrawColor
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    textDrawUseBox
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_textDrawUseBox
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    textDrawBoxColor
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_textDrawBoxColor
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    textDrawSetShadow
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_textDrawSetShadow
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    textDrawSetOutline
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_textDrawSetOutline
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    textDrawBackgroundColor
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_textDrawBackgroundColor
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    textDrawFont
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_textDrawFont
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    textDrawSetProportional
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_textDrawSetProportional
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    textDrawShowForPlayer
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_textDrawShowForPlayer
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    textDrawHideForPlayer
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_textDrawHideForPlayer
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    textDrawShowForAll
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_textDrawShowForAll
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    textDrawHideForAll
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_textDrawHideForAll
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    textDrawSetString
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_textDrawSetString
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    gangZoneCreate
 * Signature: (FFFF)I
 */
JNIEXPORT jint JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_gangZoneCreate
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    gangZoneDestroy
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_gangZoneDestroy
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    gangZoneShowForPlayer
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_gangZoneShowForPlayer
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    gangZoneShowForAll
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_gangZoneShowForAll
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    gangZoneHideForPlayer
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_gangZoneHideForPlayer
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    gangZoneHideForAll
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_gangZoneHideForAll
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    gangZoneFlashForPlayer
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_gangZoneFlashForPlayer
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    gangZoneFlashForAll
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_gangZoneFlashForAll
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    gangZoneStopFlashForPlayer
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_gangZoneStopFlashForPlayer
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    gangZoneStopFlashForAll
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_gangZoneStopFlashForAll
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    create3DTextLabel
 * Signature: (Ljava/lang/String;IFFFFIZ)I
 */
JNIEXPORT jint JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_create3DTextLabel
  (JNIEnv *, jclass, jstring, jint, jfloat, jfloat, jfloat, jfloat, jint, jboolean);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    delete3DTextLabel
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_delete3DTextLabel
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    attach3DTextLabelToPlayer
 * Signature: (IIFFF)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_attach3DTextLabelToPlayer
  (JNIEnv *, jclass, jint, jint, jfloat, jfloat, jfloat);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    attach3DTextLabelToVehicle
 * Signature: (IIFFF)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_attach3DTextLabelToVehicle
  (JNIEnv *, jclass, jint, jint, jfloat, jfloat, jfloat);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    update3DTextLabelText
 * Signature: (IILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_update3DTextLabelText
  (JNIEnv *, jclass, jint, jint, jstring);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    createPlayer3DTextLabel
 * Signature: (ILjava/lang/String;IFFFFIIZ)I
 */
JNIEXPORT jint JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_createPlayer3DTextLabel
  (JNIEnv *, jclass, jint, jstring, jint, jfloat, jfloat, jfloat, jfloat, jint, jint, jboolean);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    deletePlayer3DTextLabel
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_deletePlayer3DTextLabel
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    updatePlayer3DTextLabelText
 * Signature: (IIILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_updatePlayer3DTextLabelText
  (JNIEnv *, jclass, jint, jint, jint, jstring);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    showPlayerDialog
 * Signature: (IIILjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_showPlayerDialog
  (JNIEnv *, jclass, jint, jint, jint, jstring, jstring, jstring, jstring);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    createVehicle
 * Signature: (IFFFFIII)I
 */
JNIEXPORT jint JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_createVehicle
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat, jfloat, jint, jint, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    destroyVehicle
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_destroyVehicle
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    isVehicleStreamedIn
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_isVehicleStreamedIn
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    getVehiclePos
 * Signature: (ILnet/gtaun/shoebill/data/Vector3D;)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_getVehiclePos
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    setVehiclePos
 * Signature: (IFFF)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_setVehiclePos
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    getVehicleZAngle
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_getVehicleZAngle
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    getVehicleRotationQuat
 * Signature: (ILnet/gtaun/shoebill/data/Quaternions;)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_getVehicleRotationQuat
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    setVehicleZAngle
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_setVehicleZAngle
  (JNIEnv *, jclass, jint, jfloat);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    setVehicleParamsForPlayer
 * Signature: (IIZZ)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_setVehicleParamsForPlayer
  (JNIEnv *, jclass, jint, jint, jboolean, jboolean);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    manualVehicleEngineAndLights
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_manualVehicleEngineAndLights
  (JNIEnv *, jclass);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    setVehicleParamsEx
 * Signature: (IIIIIIII)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_setVehicleParamsEx
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    getVehicleParamsEx
 * Signature: (ILnet/gtaun/shoebill/object/VehicleParam;)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_getVehicleParamsEx
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    setVehicleToRespawn
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_setVehicleToRespawn
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    linkVehicleToInterior
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_linkVehicleToInterior
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    addVehicleComponent
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_addVehicleComponent
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    removeVehicleComponent
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_removeVehicleComponent
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    changeVehicleColor
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_changeVehicleColor
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    changeVehiclePaintjob
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_changeVehiclePaintjob
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    setVehicleHealth
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_setVehicleHealth
  (JNIEnv *, jclass, jint, jfloat);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    getVehicleHealth
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_getVehicleHealth
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    attachTrailerToVehicle
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_attachTrailerToVehicle
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    detachTrailerFromVehicle
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_detachTrailerFromVehicle
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    isTrailerAttachedToVehicle
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_isTrailerAttachedToVehicle
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    getVehicleTrailer
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_getVehicleTrailer
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    setVehicleNumberPlate
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_setVehicleNumberPlate
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    getVehicleModel
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_getVehicleModel
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    getVehicleComponentInSlot
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_getVehicleComponentInSlot
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    getVehicleComponentType
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_getVehicleComponentType
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    repairVehicle
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_repairVehicle
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    getVehicleVelocity
 * Signature: (ILnet/gtaun/shoebill/data/Velocity;)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_getVehicleVelocity
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    setVehicleVelocity
 * Signature: (IFFF)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_setVehicleVelocity
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    setVehicleAngularVelocity
 * Signature: (IFFF)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_setVehicleAngularVelocity
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    getVehicleDamageStatus
 * Signature: (ILnet/gtaun/shoebill/object/VehicleDamage;)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_getVehicleDamageStatus
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    updateVehicleDamageStatus
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_updateVehicleDamageStatus
  (JNIEnv *, jclass, jint, jint, jint, jint, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    setVehicleVirtualWorld
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_setVehicleVirtualWorld
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     net_gtaun_shoebill_samp_SampNativeFunction
 * Method:    getVehicleVirtualWorld
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_net_gtaun_shoebill_samp_SampNativeFunction_getVehicleVirtualWorld
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
